BEGIN {
    while ((getline line < arities_file) > 0) {
        record_arity(line)
    }
    close(arities_file)
    while ((getline line < overrides_file) > 0) {
        record_arity(line)
    }
    close(overrides_file)
    while ((getline line < catalog_file) > 0) {
        if (line !~ /^SYSCALL\([0-9]+, [A-Za-z0-9_]+, [0-6]U, /) {
            continue
        }
        entry = line
        sub(/^SYSCALL\([0-9]+, /, "", entry)
        name = entry
        sub(/,.*/, "", name)
        sub(/^[A-Za-z0-9_]+, [0-6]U, /, "", entry)
        sub(/\)$/, "", entry)
        details[name] = entry
    }
    close(catalog_file)
    print "/* Complete native x86-64 syscall metadata. Generated by"
    print " * tools/update-syscall-catalog.sh. Do not edit by hand. */"
    failures = 0
}

function record_arity(line, entry, fields, number, name, arity) {
    if (line !~ /^ARITY\([0-9]+, [0-6], [A-Za-z0-9_]+\)$/) {
        return
    }
    entry = line
    sub(/^ARITY\(/, "", entry)
    sub(/\)$/, "", entry)
    split(entry, fields, /, /)
    number = fields[1] + 0
    arity = fields[2] + 0
    name = fields[3]
    arity_by_name[name] = arity
    number_by_name[name] = number
}

/^SYSCALL\([0-9]+, [A-Za-z0-9_]+\)$/ {
    entry = $0
    sub(/^SYSCALL\(/, "", entry)
    sub(/\)$/, "", entry)
    split(entry, fields, /, /)
    number = fields[1] + 0
    name = fields[2]
    if (!(name in arity_by_name) || number_by_name[name] != number) {
        printf "missing x86-64 arity for syscall %d (%s)\n", number, name \
            > "/dev/stderr"
        failures++
        next
    }
    metadata = name in details ? details[name] : "0U, RESULT_INTEGER"
    printf "SYSCALL(%d, %s, %dU, %s)\n", number, name, \
           arity_by_name[name], metadata
}

END {
    if (failures != 0) {
        exit 1
    }
}
